//apply(plugin = "java")
apply(plugin = "kotlin")
apply(plugin = "kotlin-kapt")
apply(from = "$rootDir/gradle/transformer_common.gradle")
//fun DependencyHandler.`api`(dependencyNotation: Any): Dependency? = add("api", dependencyNotation)